/** @format */

import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });
const pJakartaS = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={pJakartaS.className}>{children}</body>
		</html>
	);
}
